CREATE TABLE mytable(
   id           INTEGER  NOT NULL PRIMARY KEY 
  ,act_naam     VARCHAR(31) NOT NULL
  ,artiest_id   INTEGER  NOT NULL
  ,omschrijving VARCHAR(274) NOT NULL
  ,duur         VARCHAR(8) NOT NULL
  ,type         VARCHAR(12) NOT NULL
  ,kinderen     BIT  NOT NULL
);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (1,'Alegravito',30,'Een onemanshow met veel humor in een universele taal. Een clown, onschuldig, hartverscheurend, brutaal en meester van de onzin. Veel interactie met het publiek.','45 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (52,'Ballonnenpiraat',37,'De Ballonnenpiraat uit Beveren tovert in enkele minuten de tofste figuurtjes uit zijn mouw. Zeg nu zelf welk kind is er niet blij met een reuze octopus, een mooie kat of een coole auto, … .','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (2,'Castart Rollin',9,'Deze Beverse dansvereniging, waar jezelf inleven en plezier beleven centraal staat, duikt plots op in de straten en verrast. Stilstaan wordt wel heel moeilijk!','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (3,'Chringuito Paradise',2,'Alles staat klaar voor een geslaagde openingsplechtigheid van de cocktailbar. De champagne staat koud. Maar een ongeluk schuilt altijd in een klein hoekje…','45 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (45,'Clown Poefie',22,'Clown Poefie uit Kieldrecht tovert knappe ballonfiguren uit zijn mouw.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (4,'Comme Un Vertige',31,'Op een luchtkader van 7 m hoog loert het gevaar om de hoek. Elke acrobaat tart dapper en gracieus de leegte om hem het gevoel te geven dat hij leeft. Met live rock-‘n-roll!','45 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (5,'Contra',26,'De artiesten gaan op  zoek naar hun schaduw en gaan er mee in duet of in duel, met technieken zoals acrobatie, mime, theater en maskerspel.','25 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (6,'De Bierpolitie',20,'De sympathieke agenten rijden rond in een veel te kleine interventiewagen. Besparingen! Hun alcoholcontroles zijn echter niet wat u denkt! Boetes zijn er nauwelijks, wel positieve aanbevelingen!','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (7,'De Kleinste Mobiele Cocktailbar',10,'Een interactieve, vurige en hilarische zoektocht naar mensen met ‘een alcoholtekort’. Een cocktail-consultatie waarbij de lachspieren het hard te verduren krijgen.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (8,'De Protzuiger',18,'De protzuiger, die een sterk ontwikkeld reukorgaan heeft, trekt met zijn mobiele “afzuiginstallatie” rond. Zo zorgt hij voor een genietbare leefomgeving.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (50,'De Toape Geraapte',11,'Deze rondwandelende halve garen staan garant voor grappige ontmoetingen en liederen die elke vrouw charmeren. Van snoeiharde rock tot betoverende a-capella.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (9,'Des Accords de mât',5,'Een acrobaat treft aan zijn Chinese mast een accordeonspeler aan. Een poëtische, energieke en muzikale ontmoeting, waarin het wederzijdse begrip tussen de twee groeit.','30 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (10,'Duo Traumlicht und Waldlicht',19,'De met wiegende lampionbloemen verlichte “wensdroomboom” torent op sferische klanken boven de hoofden. Met haar wiebelende lichtboom laat Fiolina ons mee genieten van de dromen, die ze van de oude bomen wegplukte.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (11,'Ekilibuâ',25,'Een koppel acteert op diverse houten haspels en combineert dit met acrobatie, messen gooien, evenwicht en objectmanipulatie.','30 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (12,'F.I.S.H.',41,'Met veel humor drijven de straffe Kapitein, de punctuele Cartograaf en de olijke Kok hun kleurrijke reuze vissen, door middel van tandwielen, kettingen en raderwerken, aan.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (13,'Familie Vestdijk',33,'De twee steltlopende stijve ouders op wandel met hun huilende baby in een te grote kinderwagen en hun zoontje van zes zijn een lust voor het  oog. De kleine humoristische acts, die zo nu en dan opvoeren, geven het geheel extra cachet.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (14,'Fantasie Van Een Droom',17,'De jonge circusartiesten Zakki en Bobo uit Beveren zijn aan het slapen. Lees de brief voor en ga mee in hun levendige dromen …','25 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (44,'Gekkefietsencircuit',43,'Scouts en Chiro Sint-Martinus On Wheels zetten drie dagen lang het centrum op stelten met knotsgek fiets plezier en diertjes op wielen. Lol trappen krijgt plots een andere betekenis.','-','activiteit',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (15,'Grime',24,'Mascara uit Beveren tovert bij de kinderen de leukste gezichten tevoorschijn.','-','activiteit',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (16,'Hippocampus',41,'De twee gladiatoren dobberen over de woelige baren. Lansen en degens worden gekruist. In oerkreten bazelen zij bezopen oneliners.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (17,'HypErion',21,'Een clownesk typetje hupt op veerstelten door de menigte en brengt alle mensen aan het gniffelen.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (18,'i-Puppets',8,'Ogen trekken aan je voorbij. De onderzoekers van deze planeet zijn vreemd, grappig en angstaanjagend.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (19,'Jackpot',41,'Een onvoorspelbaar komische gokkast uit de roerige jaren twintig met binnenin drie illustere menselijke figuren. Haal de hendel over en ze komen één voor één voorbij. Is het geluk aan uw zijde? Drie op een rij is natuurlijk … JACKPOT!','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (20,'Juffrouw Suikerspin',39,'Een sprookjesachtig typetje met haar nostalgisch suikerspinnenkraam. Gratis deelt zij suikerspinnen uit aan jong en oud.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (21,'L''Homme Canon',7,'Met heel wat vuur, pyrotechniek en kluchtigheid herneemt dit viertal de ” Kanonman”: het traditionele nummer uit de circussen van weleer.','20 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (22,'La Catastrophe Du Lapin',4,'Een steltenloper en een jongleur storten zich in een gekke wereld vol dansende kegels, balletjes … . Maar wat loopt dat verdwaald konijn daar te doen?','30 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (23,'La Factoria',16,'Slagen Roos en Salim er in, met o.a. acrobatie en vliegwerk aan de trapeze, de 8 m hoge fabriek draaiende te houden? Kunnen ze hun eerste smakelijke lolly maken?','30 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (24,'Lava Queens',33,'De prachtige Lava Queens op stelten zorgen met hun verlichte hoepelrokken voor een sprookjesachtige sfeer. Een vrolijk zonnig tafereel.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (25,'Le Funambule Striptease',29,'De voorstelling zit vol hilarische komedie, improvisatie, circustechnieken en balanceerstunts. Het publiek zet Ben Zuddhist op weg naar een vurige finale.','40 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (26,'Les Butors',6,'“Les Butors” (= de roerdompen), die vreemde ‘hoempende’ geluiden voortbrengen, laten ons genieten van hun paringsdans op de roterende ladder van 7 m hoog.','55 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (27,'Les Éclaireurs',32,'Een onbekend eiland dreigt te vergaan. Op de rug van “OISÔH”, een reuzenvogel van 7 bij 5 m, worden twee verkenners uitgestuurd om veiligere oorden op te zoeken en zo landen ze … in Beveren.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (28,'Magic White Horses',33,'Deze prachtig verlichte witte viervoeters zijn half vrouw half paard. Zij creëren een magische sprookjessfeer.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (46,'Marino Punk',23,'Vrolijke accordeonmuziek met een hoek af','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (29,'Men In Coats',28,'Een explosief duo, absurd en hilarisch. Hun handelsmerk is sprankelende visuele humor en  surrealistische slapstick die even grappig als inventief is.','25 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (30,'Mi Grande',36,'Francesco zoekt naar de beste locatie om één grote reuzenzeepbel van 5 meter lang uit zijn zeepbellenstokjes te toveren. Een visuele en interactieve act met magie en improvisatie.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (31,'Middeleeuws Tentenkamp',40,'Demonstraties van zwaardvechten en middeleeuws koken.  Kinderen zijn welkom op de kiddy battle en schietstand.','-','activiteit',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (32,'Naranja',35,'Naranja, een straattheater act op hoge stelten, is fris fruitig vrolijk. Zoet sappig en een tikkeltje zuur. Speels ondeugend en verleidelijk sensueel. Feestelijk geurend naar zomerse sinaasappels.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (33,'Opi Bench',38,'De krachtige ballonnen, die opa voor zijn kleinkind kocht, tilden hem op. Met zijn wandelstok kon hij nog net de bank vastgrijpen. Zo wacht hij nu op zijn kleinkind.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (34,'Princesse de la pinq',34,'Dit lief verlegen, schattig, sierlijk, speels clowntje danst met haar roze waaiers en glittert in het zonlicht. Een prachtige verschijning met haar lange benen.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (35,'Quoi?fuur',12,'Eénmaal langs de kappersstoel van dit kapsalon gepasseerd, zal je leven nooit meer hetzelfde zijn. Opvallen doe je! Niets is onmogelijk voor dit wacko kapsalon.','-','activiteit',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (36,'Radio Mano Sport',42,'Deze zender geeft bij elke publieke beweging live en rechtstreeks een sportverslaggeving. Tussendoor hoor je krakende vinylplaten, jingles en reclame.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (48,'Reuzen van Beveren',44,'Sefken, Diederik, Aldegonde, Cieske, Brigand, Regina, Melkboerinneke, Birken, Judocus en Lodde bekijken het feest vanuit de hoogte.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (51,'Rock au vin',45,'Een mobiele minifanfare wandelt spelend tussen de terrasjes door en brengt de muziek tot bij u. Intiem en gezellig maar evengoed ambiance en dansbaar.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (37,'Silento',3,'Dit dansduo, begeleid door een muzikant, ontdekt de sensuele liefde op de grond en aan het luchtkader. De choreografie mengt het horizontale met het verticale.','30 min','voorstelling',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (38,'Strand',18,'“Een dagje relaxen vraagt veel inspanning.” Een mimische clown act, doorspekt met slapstick en absurde humor.','30 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (49,'Tennessee Sun',13,'Met de vierkoppige band Tennessee Sun flits je terug in de tijd! Oorspronkelijk opgericht als een Johnny Cash tributeband is het repertoire inmiddels uitgebreid met pareltjes uit de jaren 50 en 60. Laat je onderdompelen in een dosis rockabilly, rock-‘n-roll en country.','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (39,'The sky is the limit',1,'Een Amsterdamse jongleur en een onbevreesde Canadese éénwielerspecialist tonen met veel humor hun veelvoudige talenten.','40 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (40,'Time To Loop',27,'Time to Loop is een verhaal over beweging, transformatie en liefde. De artiesten brengen dit op een elegante en acrobatische wijze en dit onder meer op de fiets.','30 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (47,'Tomcat',14,'Geen veredeld balorkest, wel smaakvolle covers voor jongeren én oude zakken! Op het repertoire van TomCat staat een breed spectrum aan muziek. Van pop en rock over disco en soul naar latino en zelfs house. Dansbare nummers die overgoten worden met een flinke portie ambiance','-','straatact',0);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (41,'Viva Victor',15,'Victor is jarig en krijgt van het publiek een cadeau dat uiteindelijk zijn leven zal veranderen. Visuele en absurde humor voor en in een caravan. Met publieksinteractie!','40 min','voorstelling',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (42,'Vogelbaum und Blütenfee',19,'Een statige boom en een vogel zijn één geworden. Het bevallig vogelgezichtje bazelt een eigen taaltje en tiereliert er op los. Met de wervelende dans van de mooie Aziatische pop, die kwistig kushandjes geeft, wordt de extase van de lente gevierd.','-','straatact',1);
INSERT INTO mytable(id,act_naam,artiest_id,omschrijving,duur,type,kinderen) VALUES (43,'Workshop circustechnieken',17,'Wordt zelf circusartiest en wordt het derde lid van dit vrolijke trio.','2u30 min','activiteit',1);
