CREATE TABLE mytable(
   id         INTEGER  NOT NULL PRIMARY KEY 
  ,act_id     INTEGER  NOT NULL
  ,date       VARCHAR(30)
  ,afbeelding VARCHAR(41) NOT NULL
);
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (1,1,NULL,'img/alegravito/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (2,2,NULL,'img/castart-rollin/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (3,3,NULL,'img/chringuito-paradise/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (4,4,NULL,'img/comme-un-vertige/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (5,5,NULL,'img/contra/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (6,6,NULL,'img/de-bierpolitie/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (7,7,NULL,'img/de-kleinste-mobiele-cocktailbar/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (8,8,NULL,'img/de-protzuiger/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (9,9,NULL,'img/des-accords-de-mât/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (10,10,NULL,'img/duo-traumlicht-und-waldlicht/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (11,11,NULL,'img/ekilibuâ/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (12,12,NULL,'img/F.I.S.H./1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (13,13,NULL,'img/familie-vestdijk/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (14,14,NULL,'img/fantasie-van-een-droom/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (15,15,NULL,'img/grime/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (16,16,NULL,'img/hippocampus/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (17,17,NULL,'img/hyperion/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (18,18,NULL,'img/i-puppets/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (19,19,NULL,'img/jackpot/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (20,20,NULL,'img/levend-theater/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (21,21,NULL,'img/homme-canon/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (22,22,NULL,'img/la-catastrophe-du-lapin/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (23,23,NULL,'img/la-factoria/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (24,24,NULL,'img/lava-queens/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (25,25,NULL,'img/le-funambule-striptease/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (26,26,NULL,'img/les-butors/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (27,27,NULL,'img/les-eclaireurs/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (28,28,NULL,'img/magic-white-horses/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (29,29,NULL,'img/men-in-coats/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (30,30,NULL,'img/mi-grande/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (31,31,NULL,'img/middeleeuws-tentenkamp/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (32,32,NULL,'img/naranja/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (33,33,NULL,'img/opi-bench/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (34,34,NULL,'img/princesse-de-la-pinq/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (35,35,NULL,'img/quoifuur/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (36,36,NULL,'img/radio-mano-sport/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (37,37,NULL,'img/silento/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (38,38,NULL,'img/strand/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (39,39,NULL,'img/the-sky-is-the-limit/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (40,40,NULL,'img/time-to-loop/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (41,41,NULL,'img/viva-victor/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (42,42,NULL,'img/vogelbaum-und-blütenfee/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (43,43,NULL,'img/trio-met-twee/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (44,44,NULL,'img/gekkenfietsencircuit/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (45,45,NULL,'img/clown-poefie/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (46,46,NULL,'img/marino-punk/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (47,47,NULL,'img/tomcat/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (48,48,NULL,'img/reuzen-van-beveren/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (49,49,NULL,'img/tennessee-sun/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (50,50,NULL,'img/de-toape-geraapte/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (51,51,NULL,'img/rock-au-vin/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (52,52,NULL,'img/ballonnenpiraat/1.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (53,3,NULL,'img/chringuito-paradise/2.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (54,3,NULL,'img/chringuito-paradise/3.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (55,3,NULL,'img/chringuito-paradise/4.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (56,3,NULL,'img/chringuito-paradise/5.jpg');
INSERT INTO mytable(id,act_id,date,afbeelding) VALUES (57,3,NULL,'img/chringuito-paradise/6.jpg');
